# Generated by Django 5.1.7 on 2025-03-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Job Seeker'), ('employer', 'Employer')], max_length=10),
        ),
    ]
