# Generated by Django 5.2 on 2025-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
