# Generated by Django 5.2 on 2025-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10, null=True),
        ),
    ]
