# Generated by Django 5.2 on 2025-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobvacancy_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
