# Generated by Django 5.2 on 2025-04-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_employer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
